module.exports = {
    AdminModel: require('./admin_model'),
    UserModel: require('./user_model'),
    NftModel: require('./nft_model'),
    TransactionModel: require('./transaction_model'),
    SerialModel: require('./serial_model'),
    CollectionModel: require('./collection_model'),
    CompanyModel: require('./company_model'),
    RewardModel: require('./reward_model'),
    StatisticsModel: require('./statistics_model'),
    ListenerModel: require('./listener_model'),
    HistoryModel: require('./history_model'),
    ContractModel: require('./contract_model'),
    CreatorModel: require('./creator_model'),
    TradeModel: require('./trade_model'),
    HourTradeModel: require('./hour_trade_model'),
    DayTradeModel: require('./day_trade_model'),
    SaleModel: require('./sale_model'),
    WalletModel: require('./wallet_model'),
    ProfileModel: require('./profile_model'),
    LastblockModel: require('./lastblock_model'),
};
